export const FETCH_NEWS = "FETCH_NEWS"
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS"
export const FETCH_NEWS_ERROR = "FETCH_NEWS_ERROR"

export const ADD_NEWS = "ADD_NEWS";
export const ADD_NEWS_SUCCESS = "ADD_NEWS_SUCCESS";
export const ADD_NEWS_ERROR = "ADD_NEWS_ERROR";

